### ISSUE TITLE
min-height: 55dvh; breaks layout when aspectRatio like 16/9 is specified

### ISSUE THREAD

**Issue by tobimori** [kirby-tools/kirby.tools#11]
### Environment

/

### Reproduction

```yaml
      preview:
        type: preview
        aspectRatio: 16/9
```

### Describe the bug

![CleanShot 2024-05-13 at 11 56 46@2x](https://github.com/kirby-tools/kirby.tools/assets/29142128/49d6c975-7065-43e8-9018-6aee2ded3ae3)
